services:
  app:
    image: dockerphpnginx:latest
    build: .
  sut:
    image: alpine:3.13
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
